"""initial

Revision ID: 58b26f95d8d7
Revises: 
Create Date: 2022-10-30 15:12:16.603329

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '58b26f95d8d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_table',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_table',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('check_table',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=True),
    sa.Column('user', postgresql.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['users_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction_table',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('summ', sa.Integer(), nullable=True),
    sa.Column('check', postgresql.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['check'], ['check_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_table')
    op.drop_table('check_table')
    op.drop_table('users_table')
    op.drop_table('product_table')
    # ### end Alembic commands ###
